menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/DeIonizedPlasma'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/joseph-jerkins-72271410a'}

contacts:
- {name: 'Joseph Jerkins', department: 'Plasma Science and Fusion Center', institution: 'Massachusetts Institute of Technology', institution_address: '77 Massachusetts Ave', phone: '(000) 000-0000', email: 'josephwj@mit.edu', office: 'NW17-210'}

